### ISSUE TITLE
Standardized Posteriors

### ISSUE THREAD

**Issue by DominiqueMakowski** [ecmerkle/blavaan#10]
Hi, is it possible to standardize the posterior distribution (all the draws) instead of just having the standardization of the point-estimates? Thanks a lot :)

**Comment by ecmerkle** [comment]
Please check out the new function standardizedPosterior(), available by installing from github or via

`install.packages("blavaan", repos="http://faculty.missouri.edu/~merklee", type="source")`

It was just a matter of gluing together some existing functions, but it would be helpful if you could try to break it.

**Comment by DominiqueMakowski** [comment]
Thanks!

**Comment by DominiqueMakowski** [comment]
Dear @ecmerkle, do you plan on releasing this version on CRAN? (my package has a function that depends on it) Thanks!

**Comment by ecmerkle** [comment]
I definitely plan to release it to CRAN. If it helps, I will do it sooner rather than later.

**Comment by ecmerkle** [comment]
Now on CRAN.
