### ISSUE TITLE
feature request: blavInspect(fit, "lir")

### ISSUE THREAD

**Issue by TDJorgensen** [ecmerkle/blavaan#13]
Hi Ed,

I noticed recent changes are prepping for handing ordinal outcomes.  Not to rush anything, but once that is implemented, could you make it possible to save and return draws of latent item responses, similar to making factor scores available from each iteration?  M*plus* makes these available via SAVE: LRESPONSES; so some users might like to see the same feature in `blavaan`.  For my part, I think it would be cool to open the possibility of model-based imputation of missing item-level ordinal data by saving the latent item responses instead of the imputed binary data. (Of course, you could just make your inferences from the fitted BSEM, but one might want to capitalize on established frequentist model comparison statistics by fitting competing models to the same data imputed under the most general model.)

Thanks for considering.

**Comment by ecmerkle** [comment]
I will keep this in mind, and it should be fairly easy once the models are working. This might also be obtained manually via the argument `mcmcextra=list(monitor="mu")`. But I can see the reason for adding it to blavInspect().

**Comment by ecmerkle** [comment]
An alternative here would be to adapt lavPredict to blavaan, then make "lresponses" an option there if lavaan does not already have something like that. The other lavPredict() options (the "type" argument) could be adapted to blavaan anyway, often using the lv draws in some capacity.

**Comment by ecmerkle** [comment]
I think this functionality is now covered by blavPredict(). You need to set `save.lvs = TRUE` for model estimation. But then you can use `type="yhat"` for observed variable predictions conditioned on latent variables, and `type="ypred"` for the yhat predictions plus residuals. For ordinal variables, these are on the scale of the underlying continuous variable.

```
yhat <- blavPredict(fit, type = "yhat")
ypred <- blavPredict(fit, type = "ypred")
```

And there is also `type="ymis"` for predictions of missing variables, but I think it is currently not working for ordinal variables.

**Comment by TDJorgensen** [comment]
Thanks Ed, I finally have time to explore the new features.  I read your "ordinal" vignette, so I'm slightly caught up on how many complications you had to find solutions for.  This will be a big help for my SRM software (whenever I make time for that).

I noticed a difference in the format of `blavPredict()` for factor scores (`type="lv"`) vs. these latent item responses (conditional or marginal).  

- Factor scores are stored in a matrix: 1 row per posterior sample, with vectorized factor-score matrix elements stored in columns (column names corresponding to the indices in the N*f factor-score matrix). 
- Latent item responses are returned as a list: 1 N*p matrix per posterior sample.

For `semTools::plausibleValues()`, the list of matrices is actually a more convenient format because that is what the function returns (i.e., a list of "imputed" data sets to be passed to `semTools::runMI()`, or augmented values in the case of `blavaan`).  Would it be more consistent for the output format to match (either way) across `type=` choices?  

I can work on a pull request if you agree, and let me know what format you prefer.  I expect general users might also prefer the list format used for item responses.

**Comment by ecmerkle** [comment]
That sounds reasonable to me, and it should only require an extra line or two. I have some concern that the change will break someone's code, if they are expecting the factor score output to be a matrix. On the other hand, `blavPredict` has only been around for a year or so, and many people might use the older `blavInspect(fit, 'lvs')` to get the factor scores.

**Comment by ecmerkle** [comment]
I think this issue is now addressed, but let me know if not!
