### ISSUE TITLE
use of parallel computing

### ISSUE THREAD

**Issue by ecmerkle** [ecmerkle/blavaan#14]
For mac & linux users, mclapply() is used once or twice during post-estimation computations (like in postpred()). Give the user an option to turn off parallelization in case there is some problem with parallelization (use lapply() instead).

**Comment by seonghobae** [comment]
Just switch to ```future.apply::future_lapply()``` and just set ```future::plan()``` outside of blavaan library. That’s useful to who want to use MPI or HPC computing with blavaan.
