### ISSUE TITLE
Consider estimating marginal log-likelihood in Stan?

### ISSUE THREAD

**Issue by maugavilla** [ecmerkle/blavaan#23]
Ed

I was looking at the Stan code for the pre-compile model. Have you consider add the estimation of the marginal log-likelihood in the Stan model, instead of doing that in R?

Adding in the generated quantities block something like this (i think my indexing is incorrect)
```r
##### row data log-likelihood
  if (has_data) {
    int obsidx[p + q];
    int r1;
    int r2;
    int grpidx;
    for (mm in 1:Np) {
      obsidx = Obsvar[mm,];
      r1 = startrow[mm];
      r2 = endrow[mm];
      grpidx = grpnum[mm];
       log_lik[mm] = multi_normal_lpdf(YX[r1:r2,1:Nobs[mm]] | Mu[grpidx, obsidx[1:Nobs[mm]]], Sigma[grpidx, obsidx[1:Nobs[mm]], obsidx[1:Nobs[mm]]]);
    }
#### model marginal log-likelihood
marg_log_lik = sum(log_lik); // 
```

This could be particularly useful with categorical indicators, I think would be easier to estimate this in Stan than outside

**Comment by ecmerkle** [comment]
Thanks, I need to get around to doing this. The trick is to pull the log-likelihood out of Stan for target="stan" but not for target="stanclassic", "jags", etc...

**Comment by ecmerkle** [comment]
One possible issue is that we would want a log_lik value for each person in the data. Then each person's log_lik value will receive an Rhat and n_eff computation via rstan, which can slow things down. (to get a sense of this, look at the slowdown when you estimate a model with save.lvs=TRUE vs with save.lvs=FALSE)

So I think the main question is whether the slowdown from computing Rhat and n_eff for all those log_lik values is less than the slowdown from computing all the log-likelihoods in blavaan, after estimation (where we don't have to compute Rhat and n_eff). I don't yet have a full answer here.

**Comment by maugavilla** [comment]
I tried running an example, when running the model with save.lvs did took longer than the "normal" blavaan calculation. 

Now, with the new blavaan 3.9 I get an error when save.lvs=T, with this blavaan fails to give a result
cholesky_decompose: Matrix m is not positive definite  (in 'model_stanmarg' at line 945)

This error didnt show in the previous version


### example


library(blavaan)

model <- ' 
       # latent variable definitions
         ind60 =~ x1 + x2 + x3
         dem60 =~ y1 + a*y2 + b*y3 + c*y4
         dem65 =~ y5 + a*y6 + b*y7 + c*y8
     
       # regressions
         dem60 ~ ind60
         dem65 ~ ind60 + dem60
     
       # residual correlations
         y1 ~~ y5
         y2 ~~ y4 + y6
         y3 ~~ y7
         y4 ~~ y8
         y6 ~~ y8
     '

fit <- sem(model, data=PoliticalDemocracy, meanstructure=TRUE)

newdata <- simulateData(parTable(fit), 
                        sample.nobs = 200)

#### baseline time
time_bl1 <- system.time(
  bfit <- bsem(model, data=newdata, 
               burnin=150, sample=500, 
               test="none", bcontrol=list(cores=3))
)
time_bl1[3] ## time in seconds


#### "normal"
time_bl2 <- system.time(
  bfit <- bsem(model, data=newdata, 
               burnin=150, sample=500, 
               bcontrol=list(cores=3))
)
time_bl2[3] ## time in seconds




#### save.lvs
time_bl3 <- system.time(
  bfit <- bsem(model, data=newdata, 
               burnin=150, sample=500, 
               test="none", save.lvs=TRUE,
               bcontrol=list(cores=3))
)
time_bl3[3] ## time in seconds



####
#### normal vs baseline
time_bl2[3]  - time_bl1[3]

#### save/lvs vs baseline
time_bl3[3]  - time_bl1[3]

**Comment by ecmerkle** [comment]
Was it the political democracy model that gave you the error? If so, I haven't been able to reproduce that. And does the error happen every time you run the model, or only sometimes?

**Comment by maugavilla** [comment]
The error happens when I simulate data from the Pol Dem model, and run the model in the simulated data, with save.lvs=T. It doesnt happens with the actual data, or when save.lvs=F
And happens every time, restarted R, my computer, and keeps happening



## example
library(blavaan)

model <- ' 
       # latent variable definitions
         ind60 =~ x1 + x2 + x3
         dem60 =~ y1 + a*y2 + b*y3 + c*y4
         dem65 =~ y5 + a*y6 + b*y7 + c*y8
     
       # regressions
         dem60 ~ ind60
         dem65 ~ ind60 + dem60
     
       # residual correlations
         y1 ~~ y5
         y2 ~~ y4 + y6
         y3 ~~ y7
         y4 ~~ y8
         y6 ~~ y8
     '

fit <- sem(model, data=PoliticalDemocracy, meanstructure=TRUE)

newdata <- simulateData(parTable(fit), 
                        sample.nobs = 200)

bfit <- bsem(model, data=newdata, 
             burnin=150, sample=500, 
             test="none", save.lvs=TRUE,
             bcontrol=list(cores=3))
summary(bfit)




> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] blavaan_0.3-9 Rcpp_1.0.3    lavaan_0.6-5 

loaded via a namespace (and not attached):
 [1] mvtnorm_1.1-0      lattice_0.20-40    listenv_0.8.0      prettyunits_1.1.1  runjags_2.0.4-6    ps_1.3.2          
 [7] zoo_1.8-7          assertthat_0.2.1   digest_0.6.25      R6_2.4.1           nonnest2_0.5-2     plyr_1.8.6        
[13] ggridges_0.5.2     MatrixModels_0.4-1 stats4_3.6.3       coda_0.19-3        ggplot2_3.3.0      pillar_1.4.3      
[19] rlang_0.4.5        rstudioapi_0.11    SparseM_1.78       callr_3.4.2        Matrix_1.2-18      pbivnorm_0.6.0    
[25] loo_2.2.0          munsell_0.5.0      compiler_3.6.3     rstan_2.19.3       pkgconfig_2.0.3    mnormt_1.5-6      
[31] pkgbuild_1.0.6     globals_0.12.5     mcmc_0.9-6.1       rstantools_2.0.0   tidyselect_1.0.0   tibble_2.1.3      
[37] gridExtra_2.3      codetools_0.2-16   matrixStats_0.55.0 fansi_0.4.1        future_1.16.0      crayon_1.3.4      
[43] dplyr_0.8.5        MASS_7.3-51.5      grid_3.6.3         gtable_0.3.0       lifecycle_0.2.0    magrittr_1.5      
[49] StanHeaders_2.19.2 scales_1.1.0       future.apply_1.4.0 cli_2.0.2          sandwich_2.5-1     tools_3.6.3       
[55] CompQuadForm_1.4.3 glue_1.3.1         purrr_0.3.3        processx_3.4.2     parallel_3.6.3     inline_0.3.15     
[61] colorspace_1.4-1   bayesplot_1.7.1    quantreg_5.54      MCMCpack_1.4-6    
>

**Comment by ecmerkle** [comment]
Ok, I get an occasional error when the model is fit to generated data, but not for every generated dataset. When it fails, I get some warnings (which is ok), with the error:

```
Error in if (any(blavInspect(blavaan, "neff") < 100)) { : 
  missing value where TRUE/FALSE needed
```

I wonder whether test="none" is somehow involved here and will have to check more.

More often, it just gives me warnings about "the following variables have undefined values", but I still get a blavaan object back. StanHeaders might also be involved... I am at 2.21.0-1 and you are one version behind.

**Comment by maugavilla** [comment]
Glad is not happening to you. I think this might be related to the linux version for Stanheaders, that the latest is 2.19. 
I will look into it later. 

Going back to the speed test based on estimating the log-liks inside Stan. I did some tests, and the current method is faster with larger samples (N > 1000), but with smaller samples the save.lvs=T is faster and the additional diagnotics from Stan dont slow too much

**Comment by ecmerkle** [comment]
One recent issue is that my Stan file is getting too big: for recent package versions, I have had "out of memory" errors on the windows checks, which happen during compilation of the Stan file. This has led me to move some computations from Stan to R. I may end up moving more computations to R, so that I can build up the modeling part of the Stan file while still keeping the package on CRAN.
