### ISSUE TITLE
small change needed in tests/tests.blavaanobject-methods.R

### ISSUE THREAD

**Issue by yrosseel** [ecmerkle/blavaan#28]
In lavaan dev 0.6-7, I changed the order of the arguments of lavPredict(). The second argument is now newdata= (to be consistent with predict()), instead of type=. Therefore, line 90 in tests.blavaanobject-methods.R:
```r
lavPredict(fitlav, 'lv')[,1]) > .95) 
```
should be replaced by
```r
lavPredict(fitlav, type='lv')[,1]) > .95)
```
Maybe there are more places in blavaan where this is needed (but they did not show up in my tests).
Yves.

**Comment by ecmerkle** [comment]
Thanks, should now be fixed (and I am pretty sure this was the only place).
