### ISSUE TITLE
SemPaths for blavaan

### ISSUE THREAD

**Issue by DominiqueMakowski** [ecmerkle/blavaan#3]
Hey, 

First, thanks for your package. Do you have any idea how to convert a blavaan model into something that could be plotted with the SemPlot package. I assume it would just need to somehow convert the blavaan object into a lavaan-like object?

Thanks a lot!!

**Comment by ecmerkle** [comment]
a blavaan object is basically a lavaan object with a few extra things added. So, if `fit` is a blavaan object, you might be able to do this:

`
class(fit) <- "lavaan"
`

and then call the semPlot stuff.

Ed

**Comment by seonghobae** [comment]
I add a line to do this in an automated manner. However, I do not know this commit will accept in the master branch.

Seongho
