### ISSUE TITLE
blav_object_methods.R summary back compatibility

### ISSUE THREAD

**Issue by RetoSchmucki** [ecmerkle/blavaan#35]
Hi,

When applying the summary method on a "blavaan" object computed in a previous version (0.3-15), we get this error

Error in if (blavInspect(object, "options")$prisamp) { :
  argument is of length zero

Because the object@Options$prisamp  option was not part of the blavaan object, the most recent summary function fails.

You could include a check for the prisamp option in the object, and maybe set it to FALSE if not available, so the summary works fine with fit objects computed with previous versions.

Something like (near Line 320)
if(is.null(object@Options$prisamp)) { ... }

Thanks for the great work!

**Comment by ecmerkle** [comment]
Thanks, good suggestion and I will add it soon. In the meantime, you can work around it by running this line before summary():

```
fit@Options$prisamp <- FALSE
```

(assuming fit is your fitted blavaan object)
