### ISSUE TITLE
modeling with ordered categorical variables in blavaan

### ISSUE THREAD

**Issue by littlehifive** [ecmerkle/blavaan#41]
Hi, as suggested by Prof. Ben Goodrich, I am reaching out to ask what would be the best way to model ordered categorical variables in blavaan.

For instance, I wish to build a measurement model, e.g.:

`y =~ x1 + x2 + x3` where `x1`, `x2`, `x3` are three items from the same measure measured with a Likert scale from 1-5. And my lavaan syntax is something like:

```
fit <- cfa(model, data = dat,
            ordered = c("x1", "x2", "x3"),
           estimator = "WLSMV",
           std.lv=TRUE)
```
1. Would I still be able to use the `WLSMV` estimator for ordered categorical variables if I change `cfa` to `bcfa`? The model seems to run, but I am not sure if the estimator means the same thing in a Bayesian framework.
2. Is there a way to estimate monotonic effects with blavaan, such as [what is available in brms using the `mo()` function](https://cran.r-project.org/web/packages/brms/vignettes/brms_monotonic.html#setting-prior-distributions)? 
3. I am also uncertain about the prior syntax I should use for the three items. My belief is that there are more people scoring higher scores on the Likert scale. Is `ordered_logistic()` supported in blavaan, or is there a better way?

Thank you so much!

**Comment by ecmerkle** [comment]
Ordinal variable modeling is available on the github version of blavaan, and will make it to CRAN soon. About your questions:

1. The WLSMV estimator is like an alternative to Bayesian estimation, involving least squares estimation. blavaan does the usual thing of defining the model likelihood and priors, then sampling from that model.

2. No, monotonic effects are not available. I don't think they are entirely straightforward in an SEM framework, where an observed variable could be both a predictor and response. Instead, for most models, regression relationships would involve the latent continuous variables underlying the ordinal observed variables.

3. I think this is related to question 1. If you are using the github version of blavaan, adding the `ordered` argument is enough to get an ordinal model. See the draft document below, which includes some further info about the approach and priors:

https://ecmerkle.github.io/blavaan/articles/ordinal.html

I am still working on it, so please let me know if you find problems!

**Comment by littlehifive** [comment]
Thanks so much for the advice! Following your advice, I am able to build several models. However, I am a bit confused about the difference in results in blavaan vs. in lavaan.
```
model_psra_1 <- '
 # measurement model
 PSRA =~ PSRA1_1 + PSRA2_1 + PSRA3_1 + PSRA4_1 + PSRA5_1 + PSRA6_1 + PSRA7_1 + PSRA8_1 +
                  PSRA10_1 + PSRA11_1 + PSRA12_1 + PSRA13_1

mydp <- dpriors(tau = "normal(0,0.5)",
                lambda = "normal(0,5)")

fit_psra <- bcfa(model_psra_1, data = dat_psra,
            ordered = c("PSRA1_1", "PSRA2_1", "PSRA3_1",
                        "PSRA4_1", "PSRA5_1", "PSRA6_1",
                        "PSRA7_1", "PSRA8_1", "PSRA10_1",
                        "PSRA11_1", "PSRA12_1", "PSRA13_1"),
           dp = mydp,
           std.lv=TRUE)
'
```

For results, I got something like the following. 
1. I am wondering why the blavaan estimate is the same as std.lv but different from std.all. Running the same command using lavaan seems to give estimate = std.lv = std.all.

2. Another question is on the Scales y* section: What are the meaning of these estimates? I am aware that this might be a lavaan question but I couldn't find answers anywhere. Also blavaan gives estimates < 1, but the same command in lavaan displays all estimates in this section as 1.

3. Why is MargLogLik NA? I tried to run `blavFitIndices(fit_psra, pD = "loo")` to get model fit indices, but the command takes forever to run and crashes my R session at the end.

```
blavaan (0.3-18.853) results of 1000 samples after 500 adapt/burnin iterations

  Number of observations                           777

  Statistic                                 MargLogLik         PPP
  Value                                             NA       0.000

Latent Variables:
                   Estimate  Post.SD pi.lower pi.upper   Std.lv  Std.all     Rhat    Prior     
  PSRA =~                                                                                      
    PSRA1_1           1.331    0.091    1.159    1.518    1.331    0.799    1.003   normal(0,5)
    PSRA2_1           1.076    0.074    0.936    1.230    1.076    0.733    1.002   normal(0,5)
    PSRA3_1           1.288    0.085    1.128    1.462    1.288    0.790    1.001   normal(0,5)
    PSRA4_1           1.154    0.085    1.002    1.332    1.154    0.756    1.000   normal(0,5)
    PSRA5_1           0.908    0.068    0.778    1.041    0.908    0.672    1.003   normal(0,5)
    PSRA6_1           0.643    0.060    0.531    0.764    0.643    0.541    1.002   normal(0,5)
    PSRA7_1           0.991    0.073    0.850    1.137    0.991    0.704    1.002   normal(0,5)
    PSRA8_1           1.058    0.079    0.916    1.213    1.058    0.727    1.002   normal(0,5)
    PSRA10_1          0.722    0.057    0.606    0.835    0.722    0.586    1.000   normal(0,5)
    PSRA11_1          0.653    0.072    0.515    0.799    0.653    0.547    1.000   normal(0,5)
    PSRA12_1          1.078    0.082    0.922    1.243    1.078    0.733    1.004   normal(0,5)
    PSRA13_1          0.745    0.080    0.588    0.913    0.745    0.597    1.004   normal(0,5)

...

Scales y*:
                   Estimate  Post.SD pi.lower pi.upper   Std.lv  Std.all     Rhat    Prior     
    PSRA1_1           0.601                               0.601    1.000                       
    PSRA2_1           0.681                               0.681    1.000                       
    PSRA3_1           0.613                               0.613    1.000                       
    PSRA4_1           0.655                               0.655    1.000                       
    PSRA5_1           0.740                               0.740    1.000                       
    PSRA6_1           0.841                               0.841    1.000                       
    PSRA7_1           0.710                               0.710    1.000                       
    PSRA8_1           0.687                               0.687    1.000                       
    PSRA10_1          0.811                               0.811    1.000                       
    PSRA11_1          0.837                               0.837    1.000                       
    PSRA12_1          0.680                               0.680    1.000                       
    PSRA13_1          0.802                               0.802    1.000                       
```

**Comment by ecmerkle** [comment]
I think that your questions 1 and 2 are related. First, if you are comparing to lavaan, you need to set `parameterization="theta"` in the lavaan command. Then lavaan will use identification constraints that are the same as blavaan. And this is related to the "scales": for each ordinal variable, we assume that there is an underlying continuous variable that is chopped to yield the ordinal categories. The "scale" is the variance (or SD, can't remember which) of this underlying continuous variable. That variance consists of both residual variance and variance due to latent variables.

For identification, we have to fix some part of this scale to 1. The lavaan default, "delta" parameterization, fixes the total variance to 1. The alternative used by blavaan, the "theta" parameterization, fixes the residual variance to 1.

Finally, margloglik is NA because it is more difficult to approximate in ordinal models, and the current approach for continuous data does not immediately work for ordinal variables.
