### ISSUE TITLE
lavoptions$categorical

### ISSUE THREAD

**Issue by yrosseel** [ecmerkle/blavaan#54]
Would it be possible in a future update of blavaan to replace all references to `lavoptions$categorical` by `lavInspect(object, "categorical")`?

The reason is that 'categorical' is not really an option, and is only in the lavoptions list because it is used internally in lavaan's `lav_options_set()`. I recently renamed it to `.categorical`, and noticed this broke blavaan. (I will revert this change until this is fixed).

**Comment by ecmerkle** [comment]
No problem, and I am sure I could use `lavInspect()` in even more places than this.

**Comment by ecmerkle** [comment]
Sorry, I fixed this a long time ago and never got around to sending it to CRAN. It is now finally on CRAN.
