### ISSUE TITLE
blavFitIndices & multiple groups

### ISSUE THREAD

**Issue by ecmerkle** [ecmerkle/blavaan#58]
@maugavilla @TDJorgensen I believe there is a small issue with counting parameters, around the line referenced below. Basically, there is a variable "nvar" that I think is assumed to be a single number, but it contains multiple numbers when there are multiple groups (the value is being pulled from `object@Model@nvar`). It is also used in `bgammahat` and other computations, and I am not immediately sure whether you intended multiple values there. So I think either of your eyes would be helpful!

https://github.com/ecmerkle/blavaan/blob/4b6d3bff406706e007cf52246f4aca8c04355b0d/R/ctr_bayes_fit.R#L251

One other thing: lavaan 0.6-13 does some robust fitMeasures computations, and there is a bug that leads to some errors here. It goes away if you use the github version of lavaan.

**Comment by maugavilla** [comment]
@ecmerkle  I will check on this soon
