### ISSUE TITLE
Problem with multilevel model

### ISSUE THREAD

**Issue by falkcarl** [ecmerkle/blavaan#76]
[example_dataset_77.csv](https://github.com/ecmerkle/blavaan/files/15133696/example_dataset_77.csv)

I posted a message to the Google group about this. This produces an error with blavaan, but not if doing the same model in lavaan.

dat <- read.csv("example_dataset_77.csv")
model <- '
    level: within
        y ~ X1 + X2
    level: between
        y ~ 1
'
mod.blavaan <- bsem(model = model, data = dat, cluster = "g", seed=1234)

**Comment by ecmerkle** [comment]
Thanks for the report! I believe the latest commit fixes this; instructions for installing from github are in the README. If you still have a problem, feel free to re-open.
