### ISSUE TITLE
Option to install without JAGS (i.e. only stan)

### ISSUE THREAD

**Issue by benwhalley** [ecmerkle/blavaan#8]
I'm having problems installing runjags at the moment, because of issues with the new GCC. I don't use JAGS though (just Stan) so wonder if it's possible to include an option to install choosing which backend will be used?

**Comment by ecmerkle** [comment]
This is an interesting suggestion. I think I can set it up to not require jags or stan, then throw an error if people try to use either without the required software. Will keep you posted.

**Comment by DominiqueMakowski** [comment]
That would be a very useful feature indeed :)

**Comment by ecmerkle** [comment]
ok, this should now work in the development version. Let me know if you encounter any problems:

install.packages("blavaan", repos="http://faculty.missouri.edu/~merklee", type="source")

**Comment by benwhalley** [comment]
Thanks.. that works. If you were feeling really fancy then the target option in bsem could try and autodetect what's installed.. but this is cool.
