### ISSUE TITLE
add relative effective sample size to loo

### ISSUE THREAD

**Issue by maugavilla** [ecmerkle/blavaan#9]
Hi Ed

I saw that one of the new features of the loo package was to include the relative effective sample size to the estimation of loo. By adding this to the estimation of loo, it improves the PSIS effective sample size, and the Monte Carlo error estimates. 

I edited the blavcompre function to include this for the calculation of loo, and automatically accounts for it in the comparison. This could also be added to the fitMeasures()

######
blavCompare_2 <- function (object1, object2, ...) {
  if (blavInspect(object1, "Options")$test == "none" | blavInspect(object2, "Options")$test == "none") {
    stop("blavaan ERROR: Models cannot be compared when test='none'")
  }
  bf <- object1@test[[1]]$stat - object2@test[[1]]$stat
  res <- c(bf, object1@test[[1]]$stat, object2@test[[1]]$stat)
  names(res) <- c("bf", "mll1", "mll2")
  lavopt1 <- object1@Options
  lavopt1$estimator <- "ML"
  ll1 <- case_lls(object1@external$mcmcout, object1@Model, 
                  object1@ParTable, object1@SampleStats, lavopt1, object1@Cache, 
                  object1@Data, make_mcmc(object1@external$mcmcout))
  lavopt2 <- object2@Options
  lavopt2$estimator <- "ML"
  ll2 <- case_lls(object2@external$mcmcout, object2@Model, 
                  object2@ParTable, object2@SampleStats, lavopt2, object2@Cache, 
                  object2@Data, make_mcmc(object2@external$mcmcout))
  
  if(packageVersion("loo") >= "2.0.0") {
    ### for loo package 2 or higher
    nchain1 <- length(object1@external$mcmcout$mcmc)
    nchain2 <- length(object2@external$mcmcout$mcmc)
    niter1 <- nrow(ll1)
    niter2 <- nrow(ll2)
    
    chainid1 <- NULL ## set chain id for each iteration
    for(i in 1:nchain1){
      temp <- rep(i, niter1/nchain1)
      chainid1 <- do.call(c, list(chainid1, temp))
    }
    
    chainid2 <- NULL ## set chain id for each iteration
    for(i in 1:nchain2){
      temp <- rep(i, niter2/nchain2)
      chainid2 <- do.call(c, list(chainid2, temp))
    }
    
    ref1 <- relative_eff(ll1, chain_id=chainid1) ## compute MCMC relative effective sample size
    ref2 <- relative_eff(ll2, chain_id=chainid2)
    
    loo1 <- loo(ll1, r_eff=ref1) ## compute loo including relative effective sample size
    loo2 <- loo(ll2, r_eff=ref2)
    waic1 <- waic(ll1)
    waic2 <- waic(ll2)
    
    looobj <- list(loo1$estimates, loo2$estimates)
    waicobj <- list(waic1$estimates, waic2$estimates)
  }
  else {
    loo1 <- loo(ll1)
    loo2 <- loo(ll2)
    waic1 <- waic(ll1)
    waic2 <- waic(ll2)
    
    looobj <- rbind(loo1[1:6], loo2[1:6])
    waicobj <- rbind(loo1[1:6], loo2[1:6])
  }

  diff_loo <- compare(loo1, loo2)
  diff_waic <- compare(waic1, waic2)
  cat("\nWAIC difference & SE (positive values favor object2): \n", 
      sprintf("%8.3f", diff_waic[1]), sprintf("%8.3f", diff_waic[2]), 
      "\n\n")
  cat("LOO difference & SE (positive values favor object2): \n", 
      sprintf("%8.3f", diff_loo[1]), sprintf("%8.3f", diff_loo[2]), 
      "\n\n")
  cat("Laplace approximation to the log-Bayes factor\n(experimental; positive values favor object1):", 
      sprintf("%8.3f", bf), "\n\n")

  res <- list(bf = res, loo = looobj, diff_loo = diff_loo, 
              waic = waicobj, diff_waic = diff_waic)
  
  invisible(res)
}

**Comment by ecmerkle** [comment]
This should now be added to both blavCompare() and fitMeasures() in the development version. Would be worth testing it out to make sure it works as expected.

**Comment by maugavilla** [comment]
Ed

Thanks for the quick addition. I have tested it with several models, and it seems to be working fine
